-- =================================================================================
-- SEPARAÇÃO DAS TABELAS DOS JOGOS E EXPANSÃO DE CONTEÚDO
-- =================================================================================

-- 1. Criar tabela específica para O CONSULTOR
CREATE TABLE IF NOT EXISTS public.consultor_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('good', 'bad')),
    explanation TEXT NOT NULL,
    icon TEXT,
    difficulty TEXT DEFAULT 'easy',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Criar tabela específica para DESAFIO DOS TERMOS
CREATE TABLE IF NOT EXISTS public.term_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term TEXT NOT NULL,
    definition TEXT NOT NULL,
    difficulty TEXT DEFAULT 'easy',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Habilitar RLS (Segurança)
ALTER TABLE public.consultor_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.term_questions ENABLE ROW LEVEL SECURITY;

-- 4. Criar políticas de leitura (Todos podem ler)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'consultor_questions' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON public.consultor_questions FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'term_questions' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON public.term_questions FOR SELECT USING (true);
    END IF;
END $$;

-- 5. Migrar dados antigos (se existirem na tabela antiga game_questions)
-- Consultor
INSERT INTO public.consultor_questions (text, type, explanation, icon, difficulty)
SELECT 
    content->>'text',
    content->>'type',
    content->>'explanation',
    content->>'icon',
    difficulty
FROM public.game_questions 
WHERE game_type = 'consultor';

-- Termos
INSERT INTO public.term_questions (term, definition, difficulty)
SELECT 
    content->>'term',
    content->>'definition',
    difficulty
FROM public.game_questions 
WHERE game_type = 'termo';

-- 6. Adicionar as 35 Novas Perguntas para O CONSULTOR (Totalizando 50 com as 15 antigas)
INSERT INTO public.consultor_questions (text, type, explanation, icon, difficulty) VALUES
-- Dificuldade: FÁCIL (Conceitos Básicos e Golpes Óbvios)
('Recebi um link no WhatsApp prometendo R$ 100 se encaminhar para 10 amigos. Devo clicar?', 'bad', 'Golpe de Phishing! Nenhuma empresa séria dá dinheiro em troca de spam. Você pode ter seus dados roubados.', '🎣', 'easy'),
('Pagar a fatura total do cartão de crédito ou pagar o mínimo e investir o resto?', 'good', 'Pague o total! Os juros do rotativo do cartão são absurdamente altos (mais de 300% ao ano), nenhum investimento supera isso.', '💳', 'easy'),
('Guardar dinheiro embaixo do colchão para não pagar taxas. É seguro?', 'bad', 'Péssima ideia! A inflação corrói o valor do seu dinheiro e você corre risco de roubo ou perda física.', '🛏️', 'easy'),
('Emprestar seu nome para um amigo negativado comprar um carro financiado. Ajudo?', 'bad', 'Alto risco! Se ele não pagar, a dívida é 100% sua, sujando seu nome e comprometendo seu crédito.', '🚫', 'easy'),
('Começar a investir com apenas R$ 30,00 no Tesouro Direto. Vale a pena?', 'good', 'Com certeza! O importante é criar o hábito. O tempo é o maior aliado dos juros compostos.', '🌱', 'easy'),
('Comprar um smartphone topo de linha parcelado em 24x sem juros, mas sem desconto à vista.', 'bad', 'Cuidado! Parcelas longas comprometem sua renda futura. Tente juntar e negociar desconto à vista.', '📱', 'easy'),
('O banco ofereceu aumentar meu limite do cheque especial. Devo usar como renda extra?', 'bad', 'Jamais! O cheque especial não é renda, é uma dívida com juros altíssimo. Use apenas em extrema emergência.', '🆘', 'easy'),
('Anotar todos os meus gastos diários, até o cafezinho. Preciso mesmo disso?', 'good', 'Hábito de Ouro! Saber para onde vai seu dinheiro é o primeiro passo para assumir o controle financeiro.', '📝', 'easy'),
('Investir em ações de uma empresa só porque um influenciador falou que "vai explodir".', 'bad', 'Efeito Manada! Influenciadores podem ter incentivos ocultos. Analise a empresa ou siga analistas certificados.', '🗣️', 'easy'),
('Deixar o dinheiro parado na Conta Corrente sem rendimento automático.', 'bad', 'Perda de dinheiro! A inflação faz seu saldo valer menos todo dia. Busque contas com rendimento automático (100% do CDI).', '📉', 'easy'),

-- Dificuldade: MÉDIO (Produtos Bancários e Estratégias)
('Fazer um consórcio para comprar carro porque "não tem juros". É vantajoso?', 'bad', 'Não tem juros, mas tem Taxa de Administração! Muitas vezes investir o dinheiro rende mais que pagar as taxas do consórcio.', '🤝', 'medium'),
('Comprar dólar em espécie todo mês para se proteger da crise no Brasil.', 'good', 'Estratégia válida! Ter parte do patrimônio em moeda forte (Dólar/Euro) protege seu poder de compra global.', '💵', 'medium'),
('Aceitar o "Seguro Prestamista" empurrado pelo gerente ao fazer um empréstimo.', 'bad', 'Venda Casada! Você não é obrigado a contratar. Avalie se realmente precisa dessa proteção antes de assinar.', '🏦', 'medium'),
('Investir em Fundos Multimercado para buscar rentabilidade acima do CDI.', 'good', 'Boa diversificação! Fundos multimercado podem ganhar com juros, dólar e bolsa, mas exigem pesquisa dos gestores.', '📊', 'medium'),
('Trocar de carro todo ano para não ter manutenção.', 'bad', 'Custo invisível alto! A desvalorização do veiculo novo é maior no primeiro ano e os custos de troca (documentação) são altos.', '🚗', 'medium'),
('Aportar na Previdência Privada (PGBL) para abater Imposto de Renda.', 'good', 'Inteligente! Se você faz declaração completa, o PGBL permite deduzir até 12% da renda bruta anual.', '👴', 'medium'),
('Vender suas férias (10 dias) para pagar dívidas de juros altos.', 'good', 'Decisão Racional! Trocar descanso por liberdade financeira faz sentido se for para eliminar juros abusivos.', '🏖️', 'medium'),
('Comprar ações fracionadas (Lote de 1 a 99) porque não tem dinheiro para o lote padrão.', 'good', 'Acessibilidade! O mercado fracionário permite pequenos investidores serem sócios de grandes empresas.', '🍰', 'medium'),
('Assinar 5 serviços de streaming que eu quase não assisto.', 'bad', 'Gasto Fantasma! Cancele o que não usa. R$ 50/mês investidos por 30 anos viram uma pequena fortuna.', '📺', 'medium'),
('Investir em Debêntures Incentivadas para não pagar Imposto de Renda.', 'good', 'Boa isenção! Debêntures de infraestrutura são isentas de IR para pessoa física e costumam pagar bem (IPCA+).', 'bridge', 'medium'),
('Usar o 13º salário inteiro para comprar presentes de Natal.', 'bad', 'Planejamento ruim! O 13º deve ser usado prioritariamente para pagar dívidas, IPVA/IPTU ou investir.', '🎁', 'medium'),
('Antecipar a restituição do Imposto de Renda pelo banco.', 'bad', 'Cuidado! Isso é um empréstimo com juros. Espere a Receita pagar, a não ser que precise muito do dinheiro.', '🦁', 'medium'),

-- Dificuldade: DIFÍCIL (Conceitos Avançados e Armadilhas Sutis)
('Alugar Ações (Doador) para ganhar uma taxa extra na carteira de longo prazo.', 'good', 'Renda Extra! Se você não pretende vender as ações, alugá-las gera uma taxa pequena sem perder os dividendos.', '🤝', 'hard'),
('Fazer "Preço Médio" comprando mais ações de uma empresa que perdeu seus fundamentos.', 'bad', 'Ancoragem! Não jogue dinheiro bom em negócio ruim. Se a empresa piorou, o barato pode sair caro.', '⚓', 'hard'),
('Investir em ETFs (Fundo de Índice) em vez de escolher ações individuais (Stock Picking).', 'good', 'Eficiência! A maioria dos gestores não bate o índice. ETFs garantem diversificação e baixo custo.', '🌐', 'hard'),
('Operar Opções sem conhecimento para tentar "alavancar" os ganhos.', 'bad', 'Cemitério de Malandro! Derivativos têm risco de perda total (virar pó). Estude muito antes ou use apenas para proteção (Hedge).', '💣', 'hard'),
('Resgatar o investimento antes do vencimento (Marcação a Mercado).', 'bad', 'Perda provável! Na Renda Fixa, sair antes pode dar prejuízo se os juros subiram. Leve até o vencimento para garantir a taxa contratada.', '📅', 'hard'),
('Ter criptomoedas em uma "Cold Wallet" (carteira física) em vez de deixar na corretora.', 'good', 'Segurança Máxima! "Not your keys, not your coins". Corretoras podem ser hackeadas ou falir.', '🔐', 'hard'),
('Ignorar a inflação e olhar apenas para o rendimento nominal.', 'bad', 'Ilusão Monetária! O que importa é o Ganho Real (Juros - Inflação). 10% de ganho com 10% de inflação é zero.', '🎈', 'hard'),
('Contratar um Consultor Financeiro Independente (CFP) pago, em vez do assessor "gratuito" da corretora.', 'good', 'Isenção! O consultor pago trabalha para VOCÊ. O "gratuito" ganha comissão dos produtos que te vende (conflito de interesses).', '🧑‍💼', 'hard'),
('Acreditar que "Imóvel nunca desvaloriza".', 'bad', 'Mito! Bairros degradam, liquidez é baixa e custos de vacância existem. Imóveis podem sim perder valor real.', '🏚️', 'hard'),
('Usar a regra dos 50-30-20 para dividir o orçamento (Essenciais, Desejos, Investimentos).', 'good', 'Equilíbrio! Uma das melhores regras práticas para manter a saúde financeira sem viver na miséria.', '⚖️', 'hard'),
('Investir em empresas ESG (Ambiental, Social e Governança) visando sustentabilidade.', 'good', 'Tendência Global! Empresas responsáveis tendem a ter menos riscos jurídicos e melhor imagem no longo prazo.', '♻️', 'hard'),
('Manter todo o patrimônio no Brasil (Risco Brasil).', 'bad', 'Concentração de Risco! Tenha parte do patrimônio no exterior para se proteger de crises políticas/econômicas locais.', '🇧🇷', 'hard'),
('Fazer seguro do carro apenas contra roubo e furto, ignorando terceiros.', 'bad', 'Economia Porca! Se você bater em um carro de luxo, a dívida pode acabar com seu patrimônio. Tenha cobertura para terceiros.', '💥', 'hard');

-- 7. (Opcional) Dropar a tabela antiga se quiser limpar, ou manter como backup
-- DROP TABLE public.game_questions;
